name: dupe
description: НИР

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  drag_and_drop_lists: ^0.2.1
  sqflite: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  io: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
